# Generated by Django 5.2.3 on 2026-03-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('game_name', models.CharField(blank=True, max_length=255, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('absolute_score', models.FloatField(blank=True, null=True)),
                ('percentage_score', models.FloatField(blank=True, null=True)),
                ('game_session_data', models.TextField(blank=True, null=True)),
                ('words_played', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gameresults',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordDataset',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('anchor_word', models.CharField(max_length=255)),
                ('synonym1', models.CharField(blank=True, max_length=255, null=True)),
                ('synonym2', models.CharField(blank=True, max_length=255, null=True)),
                ('synonym3', models.CharField(blank=True, max_length=255, null=True)),
                ('synonym4', models.CharField(blank=True, max_length=255, null=True)),
                ('antonym1', models.CharField(blank=True, max_length=255, null=True)),
                ('antonym2', models.CharField(blank=True, max_length=255, null=True)),
                ('antonym3', models.CharField(blank=True, max_length=255, null=True)),
                ('antonym4', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sortonym_words',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OtpChallenge',
        ),
    ]
